### ISSUE TITLE
Netlify Forms の Honeypot field によるスパム対策を入れたい

### ISSUE THREAD

**Issue by dynamis** [videomark/videomark.webdino.org#2]
お問い合わせには従来通り Netlify フォームを利用している
https://github.com/videomark/videomark.webdino.org/blob/main/src/routes/(marketing)/%5Blocale%3Dlocale%5D/(default)/contact/%2Bpage.svelte

が Netlify の `netlify-honeypot` 属性で指定可能なスパムフィルタ用フィールドを活用していない。

netlify-honeypot 属性でしていた名前のフィールドを CSS で隠して入れておくと、ボットの投稿は間違ってそこに入力することでフィルタされるという仕組み。
https://docs.netlify.com/forms/spam-filters/

サンプルコード通り bot-field では意味がなくて、ボットが間違って入力するようなフィールド名に netlify-honeypot 属性の設定自体も変える必要はある。

**Comment by kyoshino** [comment]
現状スパムがほとんど来てないなら特に対策しなくて良いような気がしますが、Netlify でビルドされてないサイトではハニーポットは多分使えず、[独自に reCAPTCHA 2 を埋め込む](https://docs.netlify.com/forms/spam-filters/#custom-recaptcha-2) しかないようです。

せっかく Cloudflare に移行するなら CAPTCHA 代替の [Turnstile](https://blog.cloudflare.com/turnstile-private-captcha-alternative/) 使ってみましょう。

**Comment by kyoshino** [comment]
Turnstile は使うの若干難しいかも。ワーカーなり使ってサーバーサイドで secret key を隠さないといけない。

> Netlify でビルドされてないサイトではハニーポットは多分使えず

Netlify に今のサイト (あるいは新しいサイト) そのまま残せば良い話ですね。`<input name="bot-field" />` が欠けているのは簡単に修正できるので。

**Comment by dynamis** [comment]
> Netlify に今のサイト (あるいは新しいサイト) そのまま残せば良い話ですね。

はい。今のサイトそのまま残すのはノイジーで後でフォーム編集しようとする人が迷うので、既存のものはブランチ切って残した上で main ブランチはまるっと消して _redirects と form.html 程度だけにしたものをデプロイする想定です。
